### ISSUE TITLE
Structerized Post Section

### ISSUE THREAD

**Issue by user-64bit** [arth2002/my-tweetfolio#3]
As you can see on the post section of the [website](https://arthprajapati.netlify.app/posts).
Posts are not Structured So I want to make them a little bit in a structured format.

I've used Iframely to make posts like that.
so You can check that out too.

Thanks

**Comment by Misterr-H** [comment]
@arth2002 Hey, I would like to work on it.

**Comment by user-64bit** [comment]
Sure. You can work on this @Misterr-H 
Thanks for your help.

Don't forget to star :star:  this repo
Thanks :smiley:

**Comment by Misterr-H** [comment]
@arth2002 On it. Thanks

**Comment by Misterr-H** [comment]
<img width="1016" alt="Screenshot 2022-10-01 at 2 19 17 PM" src="https://user-images.githubusercontent.com/55010619/193401393-4bd29e49-dd17-4fba-ba63-e959aea2ec4a.png">

Hello @arth2002 . I hope u will like my work.
Since you were using Iframely which will costs you, I've used jsonlink.io to extract meta information from links and created my own separate cards using the fetched information.
I've created a separate component BlogCard.js and used it inside Blog.js.

This is my first open source contribution of my life, please review my code and merge.

**Comment by Misterr-H** [comment]
#5

**Comment by Misterr-H** [comment]
@arth2002 
Also please add hacktoberfest label to your repository too.
not just on issues.

**Comment by user-64bit** [comment]
Sure, Don't worry about that.
By the way, You've done a tremendous job. :1st_place_medal: 
Thanks for your contribution. :smiley: 
I'll be merging in a few minutes. :+1:

**Comment by Misterr-H** [comment]
@arth2002 Thankyou very much😊
